### ISSUE TITLE
.flat() error in Firefox

### ISSUE THREAD

**Issue by niziak** [timoschwarzer/gitlab-monitor#105]
GUI is not working in Firefox (Debian Buster version 60.9.0esr). 
GUI is working well in Chrome (Version 77.0.3865.90 (Official Build) (64-bit))
Debug console:
```
[HMR] Waiting for update signal from WDS...
log.js:24
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
vue.runtime.esm.js:8434
[Vue warn]: Cannot find element: #app
vue.runtime.esm.js:619
warn
vue.runtime.esm.js:619
query
vue.runtime.esm.js:5665
Vue.prototype.$mount
vue.runtime.esm.js:8408
initMixin/Vue.prototype._init
vue.runtime.esm.js:5012
Vue
vue.runtime.esm.js:5079
finish
main.js:21
_callee$
main.js:36
tryCatch
runtime.js:45
invoke
runtime.js:271
defineIteratorMethods/</prototype[method]
runtime.js:97
asyncGeneratorStep
asyncToGenerator.js:5
_throw
asyncToGenerator.js:31
run
es6.promise.js:75
notify/<
es6.promise.js:92
flush
_microtask.js:18

Unhandled promise rejection 
TypeError: [...].flat is not a function
Stack trace:
_callee$@webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/app.vue?vue&type=script&lang=js&:147:27
tryCatch@webpack-internal:///./node_modules/regenerator-runtime/runtime.js:45:37
invoke@webpack-internal:///./node_modules/regenerator-runtime/runtime.js:271:22
defineIteratorMethods/</prototype[method]@webpack-internal:///./node_modules/regenerator-runtime/runtime.js:97:16
asyncGeneratorStep@webpack-internal:///./node_modules/@babel/runtime-corejs2/helpers/esm/asyncToGenerator.js:9:16
_next@webpack-internal:///./node_modules/@babel/runtime-corejs2/helpers/esm/asyncToGenerator.js:31:9
_asyncToGenerator/</<@webpack-internal:///./node_modules/@babel/runtime-corejs2/helpers/esm/asyncToGenerator.js:38:7
Promise@webpack-internal:///./node_modules/core-js/library/modules/es6.promise.js:177:7
_asyncToGenerator/<@webpack-internal:///./node_modules/@babel/runtime-corejs2/helpers/esm/asyncToGenerator.js:27:12
fetchProjects@webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/app.vue?vue&type=script&lang=js&:236:16
reloadConfig@webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/app.vue?vue&type=script&lang=js&:306:9
beforeMount@webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/app.vue?vue&type=script&lang=js&:106:5
invokeWithErrorHandling@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1853:49
callHook@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4207:7
mountComponent@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4031:3
Vue.prototype.$mount@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:8399:10
init@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3115:7
createComponent@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:5962:9
createElm@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:5909:9
patch@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:6500:9
lifecycleMixin/Vue.prototype._update@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3933:16
updateComponent@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4054:7
get@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4467:13
Watcher@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4456:7
mountComponent@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4061:3
Vue.prototype.$mount@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:8399:10
initMixin/Vue.prototype._init@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:5002:7
Vue@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:5069:3
finish@webpack-internal:///./src/main.js:46:3
_callee$@webpack-internal:///./src/main.js:79:11
tryCatch@webpack-internal:///./node_modules/regenerator-runtime/runtime.js:45:37
invoke@webpack-internal:///./node_modules/regenerator-runtime/runtime.js:271:22
defineIteratorMethods/</prototype[method]@webpack-internal:///./node_modules/regenerator-runtime/runtime.js:97:16
asyncGeneratorStep@webpack-internal:///./node_modules/@babel/runtime-corejs2/helpers/esm/asyncToGenerator.js:9:16
_throw@webpack-internal:///./node_modules/@babel/runtime-corejs2/helpers/esm/asyncToGenerator.js:35:9
run@webpack-internal:///./node_modules/core-js/library/modules/es6.promise.js:75:22
notify/<@webpack-internal:///./node_modules/core-js/library/modules/es6.promise.js:92:30
flush@webpack-internal:///./node_modules/core-js/library/modules/_microtask.js:18:9
es6.promise.js:110
onUnhandled/</result<
es6.promise.js:110
module.exports
_perform.js:3
onUnhandled/<
es6.promise.js:104
module.exports
_invoke.js:5
<anonymous>
_task.js:35
run
_task.js:21
listener
_task.js:25
```

**Comment by timoschwarzer** [comment]
Hi niziak!
Firefox has support for `Array.flat()` since version 62.
You should be able to use the non-ESR Firefox version from the Debian repos.
